### ISSUE TITLE
本地钱包

### ISSUE THREAD

**Issue by PetersonZhao** [PetersonZhao/remote_code#2]
### 1.生成助记码与私钥

点击按钮进入地址生成器
![image](https://user-images.githubusercontent.com/32428724/53320122-99415880-390f-11e9-9bd0-dd7c1572ab99.png)

![image](https://user-images.githubusercontent.com/32428724/53320173-c4c44300-390f-11e9-850d-33ca8aabf6c3.png)
如果，首次使用，并没有助记码，可以点击”生成助记码“。

#### 助记码ID

因为地址生成后无任何识别特征，为了将地址与生成它的助记码对应，引入助记码ID，此ID为唯一ID，故运营人员在填写这一项时，需要在资管后台查询自己的”私钥ID“

#### 地址索引

地址索引在每个助记码下为唯一值，运营人员在生成私钥的时候，需要在资管平台查询自己已经用掉的索引，往后顺延即可

#### 地址类型

地址类型分为出币和入币，入币地址为机构入金地址，禁止运营人员生成此类地址；出币地址为调仓等其他类型的地址

#### ⚠️生成地址需要消耗大量的cpu资源，建议使用4核心标准电压的cpu⚠️

**Comment by VVanaheim** [comment]
钱包系统研发繁琐复杂，感觉现在大家都在用优盾钱包了

**Comment by PetersonZhao** [comment]
> 钱包系统研发繁琐复杂，感觉现在大家都在用优盾钱包了

很多小公司会使用第三方钱包，但是从安全角度上来看，还是自研的钱包比较安全
